apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-05-08T15:12:05Z"
  generation: 1
  labels:
    app: manageemployees-dplmnt
  name: manageemployees-dplmnt
  namespace: default
  resourceVersion: "9802"
  uid: 2075d8a9-491c-4959-9703-2071984a3882
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: manageemployees-dplmnt
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: manageemployees-dplmnt
    spec:
      containers:
      - image: localhost:5000/manageemployees:v2
        imagePullPolicy: IfNotPresent
        name: manageemployees
        ports:
        - containerPort: 9090
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-08T15:12:07Z"
    lastUpdateTime: "2025-05-08T15:12:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-08T15:12:05Z"
    lastUpdateTime: "2025-05-08T15:12:07Z"
    message: ReplicaSet "manageemployees-dplmnt-694df78b5c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
