apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-08T15:22:49Z"
  labels:
    app: manageemployees-dplmnt
  name: manageemployees-svc
  namespace: default
  resourceVersion: "9997"
  uid: 0d36cf67-2fa5-4bf3-9866-0eed84672109
spec:
  clusterIP: 10.43.22.199
  clusterIPs:
  - 10.43.22.199
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32340
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: manageemployees-dplmnt
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
