apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-07T09:31:28Z"
  labels:
    app: greeting-dplmnt
  name: greeting-svc
  namespace: default
  resourceVersion: "6272"
  uid: 8ff015c0-389c-490d-8400-81049b1f99b7
spec:
  clusterIP: 10.43.123.146
  clusterIPs:
  - 10.43.123.146
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30684
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: greeting-dplmnt
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
